<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>12.0</LangVersion>
    <AssemblyName>QuickSearch</AssemblyName>
    <RootNamespace>QuickSearch.Windows</RootNamespace>
    <Platforms>x64</Platforms>
    <PlatformTarget>x64</PlatformTarget>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <ApplicationIcon>Assets\QuickSearch.ico</ApplicationIcon>
    <Version>0.0.2</Version>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\QuickSearch.Core\QuickSearch.Core.csproj" />
    <PackageReference Include="WPF-UI" Version="4.3.0" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Assets\QuickSearch.ico" />
  </ItemGroup>
  <ItemGroup Condition="Exists('native\Everything64.dll')">
    <Content Include="native\Everything64.dll"
             Link="Everything64.dll"
             CopyToOutputDirectory="PreserveNewest"
             CopyToPublishDirectory="PreserveNewest" />
  </ItemGroup>
  <ItemGroup Condition="Exists('dependencies\Everything-Setup.exe') And Exists('dependencies\Everything-Setup.sha256')">
    <Content Include="dependencies\Everything-Setup.exe"
             Link="dependencies\Everything-Setup.exe"
             CopyToOutputDirectory="PreserveNewest"
             CopyToPublishDirectory="PreserveNewest" />
    <Content Include="dependencies\Everything-Setup.sha256"
             Link="dependencies\Everything-Setup.sha256"
             CopyToOutputDirectory="PreserveNewest"
             CopyToPublishDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
